_target_: pytorch_lightning.Trainer
gradient_clip_val: 0.5
accelerator: gpu
devices: 1
logger:
  _target_: pytorch_lightning.loggers.CSVLogger
  save_dir: ${hydra:run.dir} #/home/triet/Bureau/EEG/code/learned_preconditioning_esi/exps
#  name: ${hydra:runtime.choices.xp}
  version: ''
max_epochs: 500
callbacks:
  - _target_: pytorch_lightning.callbacks.ModelCheckpoint
    monitor: val/outer_loss #val_mse
    save_top_k: 3
    filename: '{loss:.5f}-{epoch:03d}'
  - _target_: pytorch_lightning.callbacks.ModelSummary
    max_depth: 2

